### ISSUE TITLE
Add explanation for pH measurement

### ISSUE THREAD

**Issue by richardatsap** [aweijnitz/recipe-el_fuego_viviente#2]
You maybe should add a few words to explain the pH measurement shown. Why and at which stage did you do it and what was the outcome.  For the fermented stuff I'd expect a lower pH than shown (that would also help for preventing botulism). I see the reading as not being less than 5 which would be a bit too high in my book.

Otherwise, great stuff (I make sour dough bread weekly, so I enjoyed it).

**Comment by aweijnitz** [comment]
Makes sense. I will try to work it in.

The picture is not great, as the camera added (uneven) saturation. I had the reading at 3 - 4, which was also supported by the very active fermentation and the quite sharp acidic taste of the brine.

I know there is always a small risk of botulism, but in reality (supported by statistics) it is not a big risk.
