### ISSUE TITLE
[field report] Creating my own open sauce 🌶

### ISSUE THREAD

**Issue by eddex** [aweijnitz/recipe-el_fuego_viviente#22]
I just finished my first batch of hot sauce following this recipe. I want to quickly document my process and how it turned out for me.

## Preparations

The bell chilies I harvested from my own plants were not enough, so I bought some more at the local farmers marked.
In the end I used a mix of several different chilies, including:
- small bell chillies
- large bell chillies
- mini bell peppers
- habaneros
- and some more (all not very spicy)

Before starting I watched [the video](https://www.youtube.com/watch?v=UGjCeAbWKPo) in the _preparation tips_, which was really helpful.

**Lesson learned**: What I didn't do was to wear gloves. I could feel the burn of the habaneros for the rest of the day in my finger tips. So next time this would not be the worst idea. 😄 

![2022-09-10 16 09 21](https://user-images.githubusercontent.com/5302085/192091853-33f12921-76d6-466e-b02a-bc9a87abe30b.jpg)

I decided to make two batches, one with and one without habaneros and let them ferment for two weeks. Both jars were washed in the dishwasher to make sure they are sterile (at least enough for the fermentation process).

## Fermentation

To make sure the jars don't get too much sunlight, I placed them in a cupboard in my kitchen. I checked on them every day and opened the jar briefly to let the built up gasses out. The smell of the gasses was not great, but I guess that's normal.

When I opened the jars after roughly the 2nd day, a lot of bubbles started to rise to the top. This got gradually less until after a week or so, there were no bubbles anymore when I opened the jars. There was also less and less gas building from day to day. I was a bit worried that this could be a bad sign, so I decided to check the pH after the fermentation process.

**Tip**: I set a reminder on my phone every day to make sure I don't forget opening the jars. They build up a lot of pressure!

https://user-images.githubusercontent.com/5302085/192092658-db39ff8d-5b84-47dd-be90-842713ef2402.mp4

What I also noticed was that towards the end of the fermentation process, some yeast was building at the bottom of the jars. In [the video](https://www.youtube.com/watch?v=UGjCeAbWKPo) Brad mentions that this can happen on top of the liquid. But I guess it doesn't matter where it starts to build. Nothing to be worried about.

![2022-09-23 17 48 51](https://user-images.githubusercontent.com/5302085/192092428-79d2f731-04fa-4254-befc-93b1b6cd525b.jpg)

## Bottling

After 14 days, I tested both jars for their pH value and both were clearly below 5, maybe even below 4.5 but the reference scale on my test kit doesn't go any lower. Anyhow, this is a good sign.

![2022-09-24 11 24 17](https://user-images.githubusercontent.com/5302085/192092771-0e3ddaea-6538-47c6-9667-9b3d39f8a56d.jpg)

## Conclusion

The end result turned out very good. After blending, I only added a little bit of the brine to slightly change the consistency. The sauce without habaneros turned out to be not spicy at all. It tastes a lot more salty than the one with habaneros. The habanero sauce is clearly my favorite of the two.

![2022-09-24 11 25 25](https://user-images.githubusercontent.com/5302085/192092807-383a682f-6258-4285-ad28-851a8e36a0f6.jpg)

The whole process is very easy and the result is great. I can recommend anyone who loves hot sauce to try this.

Thanks for the recipe and the inspiration! 🌶

**Comment by aweijnitz** [comment]
Nice! Thanks for the report! On the saltiness, I feel there is a lot of room for tweakability of the base recipe. Very cool to read a field report. Thanks again!
