### ISSUE TITLE
Sauce code

### ISSUE THREAD

**Issue by lhypl** [aweijnitz/recipe-el_fuego_viviente#5]
Where is the sauce code? I could compile the chilli sauce right? The instructions didn't provide any ingredients :rainbow:

**Comment by aweijnitz** [comment]
For this repo, we must understand transitive verb _to compile_ in it's non-technical [meaning](https://www.merriam-webster.com/dictionary/compile). In short it is a composition of gathered materials, to form a sauce. 

**Resolution:** Close Won't Fix. Works as intended. :-)
